name: 🚀 Deploy (pull always, restart backend only if needed)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/live-demo/kanap
            git pull origin main

            # Vérifie si des fichiers dans back/ ont été modifiés dans le dernier commit
            if git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) | grep '^back/'; then
              echo "📦 Modifications détectées dans back/, on redémarre..."
              screen -S kanap-backend -X quit || true
              cd back
              screen -dmS kanap-backend bash -c "npm install && npm start"
            else
              echo "✅ Aucun changement dans back/, pas de redémarrage."
            fi
          EOF
